### ISSUE TITLE
veri cool bro

### ISSUE THREAD

**Issue by popchenk** [JunekCZ/slate-demo#1]

**Comment by popchenk** [comment]
![IMG_6484](https://github.com/user-attachments/assets/048f73ef-c793-474c-8f7b-373e850c3c6c)

**Comment by JunekCZ** [comment]
Bruh, co me sledujes 💀💀
Snazim se vytvorit minimal-reproducible projekt

**Comment by popchenk** [comment]
ok, thank you for fixing this issue
